Allow deleting comment from the frontend
googleinterns/step203-2020 pull request #102
Opened 2020-07-22 04:18 UTC by limli

![Screenshot 2020-07-22 at 12 16 00 PM](https://user-images.githubusercontent.com/39252823/88133628-20822100-cc15-11ea-8fda-69ed6691f482.png)
![Screenshot 2020-07-22 at 12 17 34 PM](https://user-images.githubusercontent.com/39252823/88133734-5a532780-cc15-11ea-9987-3eac0fc58b5a.png)

2020-07-22 06:26 UTC, jyx11011 submitted a review, later dismissed

2020-07-22 08:23 UTC, SuyashLakhotia requested changes

2020-07-22 08:23 UTC, SuyashLakhotia commented on src/main/webapp/js/go-to-deal.js
> +  contentElement.className = `flex-grow-1 d-flex flex-column
nit: If you use template literals here, it will add a lot of whitespace before `justify-content-between`. Maybe just use a regular string?

2020-07-23 01:58 UTC, SuyashLakhotia approved these changes

2020-07-23 02:43 UTC, merged