Front end for sorting deals from each section
googleinterns/step203-2020 pull request #135
Opened 2020-07-28 09:52 UTC by lisasgoh

![Screenshot 2020-07-28 at 5 51 43 PM](https://user-images.githubusercontent.com/42923450/88650128-06f04600-d0fb-11ea-8e27-6aa52c658c70.png)

2020-07-29 03:23 UTC, jyx11011 submitted a review, later dismissed

2020-08-03 04:49 UTC, anuragshirolkar requested changes

2020-08-03 04:49 UTC, anuragshirolkar commented on src/main/webapp/js/all-section-deals.js
> +  if (reqSection !== 'trending') {
I didn't understand why reqSection `trending` has separate behavior. Could you add a comment with some explanation?

2020-08-04 10:14 UTC, anuragshirolkar submitted a review, later dismissed

2020-08-07 12:46 UTC, anuragshirolkar approved these changes

2020-08-07 12:48 UTC, merged