add validation for deal
googleinterns/step203-2020 pull request #18
Opened 2020-07-01 05:04 UTC by limli

2020-07-06 06:25 UTC, jyx11011 commented on src/main/java/com/google/step/servlets/DealDetailServlet.java
> +    } catch (NumberFormatException e) {
can also catch an index out of bound exception thrown by substring method here

2020-07-06 07:29 UTC, SuyashLakhotia commented
Please add tests! :)

2020-07-06 07:29 UTC, SuyashLakhotia requested changes
Please add the appropriate tests for the servlet.

2020-07-06 07:40 UTC, limli commented
> Please add the appropriate tests for the servlet.

@SuyashLakhotia the tests are inside another branch https://github.com/googleinterns/step203-2020/tree/deal-test for json test and https://github.com/googleinterns/step203-2020/tree/deal-test-servlet for servlet test, which is checkout-ed from branch user-test. Should I merge the branches to here?

2020-07-06 08:18 UTC, SuyashLakhotia commented
@limli Thanks for the pointer! I think we should coordinate with @jyx11011 to get her PRs that you're dependent on merged into `master` so that you can add the tests in this PR alongside the code and merge it together.

However, don't merge `user-test` into this branch (unless it's already merged with `master`) because that will make the diff super hard to read.

2020-07-07 06:59 UTC, limli commented
@SuyashLakhotia the POST servlet tests are added. The tests for the other servlets, as well as the tests for the JsonFormatter and datastore can be done in another PR.

2020-07-07 07:29 UTC, SuyashLakhotia requested changes

2020-07-07 07:29 UTC, SuyashLakhotia commented on src/main/java/com/google/step/servlets/DealDetailServlet.java
> +    long poster = -1;
```suggestion
    long posterId = -1;
```

2020-07-07 07:29 UTC, SuyashLakhotia commented on src/main/java/com/google/step/servlets/DealDetailServlet.java
> +    long restaurant = -1;
```suggestion
    long restaurantId = -1;
```

2020-07-07 07:29 UTC, SuyashLakhotia commented on src/main/java/com/google/step/servlets/DealPostServlet.java
>      long poster = 1234; // TODO get authenticated user
```suggestion
    long posterId = 1234; // TODO get authenticated user
```

2020-07-07 07:29 UTC, SuyashLakhotia commented on src/main/java/com/google/step/servlets/DealPostServlet.java
> +    long restaurant;
```suggestion
    long restaurantId;
```

2020-07-07 07:29 UTC, SuyashLakhotia commented on src/test/java/com/google/step/servlets/DealPostServletTest.java
> +  public void testDoPost_sucess() throws IOException {
```suggestion
  public void testDoPost_success() throws IOException {
```

2020-07-07 07:29 UTC, SuyashLakhotia commented on src/test/java/com/google/step/servlets/DealPostServletTest.java
> +    verify(response, never()).setStatus(HttpServletResponse.SC_BAD_REQUEST);
Verify status is `SC_OK`? Add this to the servlet if not already the case.

2020-07-07 07:29 UTC, SuyashLakhotia commented on src/test/java/com/google/step/servlets/DealPostServletTest.java
> +    verify(response, never()).setStatus(HttpServletResponse.SC_BAD_REQUEST);
You should also verify that the DealManager is being invoked correctly here.

2020-07-08 06:33 UTC, SuyashLakhotia submitted a review, later dismissed

2020-07-08 06:33 UTC, SuyashLakhotia commented on src/test/java/com/google/step/servlets/DealPostServletTest.java
> +    verify(response, never()).setStatus(HttpServletResponse.SC_BAD_REQUEST);
You can remove this line now.

2020-07-08 07:08 UTC, SuyashLakhotia approved these changes

2020-07-08 07:08 UTC, merged