Authentication servlet
googleinterns/step203-2020 pull request #26
Opened 2020-07-03 01:43 UTC by jyx11011

This PR was approved earlier but it was not merged to master.

2020-07-03 03:19 UTC, limli commented
can you `git merge master`? When I checkout this branch, it can't be compiled because of a syntax error in the `web.xml` file

2020-07-06 02:02 UTC, limli reviewed
looks good to me

2020-07-07 06:32 UTC, anuragshirolkar requested changes

2020-07-07 06:32 UTC, anuragshirolkar commented on src/main/webapp/WEB-INF/web.xml
> +<<<<<<< HEAD
Looks like there's merge conflict.

2020-07-07 06:32 UTC, SuyashLakhotia commented on src/main/webapp/WEB-INF/web.xml
> +<<<<<<< HEAD
Seems like there are unresolved merge conflicts?

2020-07-08 14:11 UTC, anuragshirolkar approved these changes

2020-07-09 01:24 UTC, merged