Add a test util class
googleinterns/step203-2020 pull request #27
Opened 2020-07-03 03:09 UTC by jyx11011

Add a test util class with some constants
More fields can be added later

2020-07-03 03:30 UTC, limli commented
looks good to me

2020-07-03 03:43 UTC, limli submitted a review, later dismissed

2020-07-03 09:37 UTC, SuyashLakhotia approved these changes

2020-07-03 09:37 UTC, SuyashLakhotia requested changes
Instead of calling it `TestUtil`, you can call it `TestConstants`. The term "util" is usually used for helper methods.

2020-07-06 07:15 UTC, SuyashLakhotia approved these changes

2020-07-06 08:46 UTC, merged