Comment manager
googleinterns/step203-2020 pull request #29
Opened 2020-07-03 07:08 UTC by lisasgoh

Add CommentManager interface and CommentManagerDatastore implementation, as well as Get, Post, Delete, Update endpoints for CommentServlet with tests for both CommentManagerDataStore and CommentServlet

2020-07-03 07:55 UTC, limli reviewed
change according to the design doc that we just discussed on chat

2020-07-03 08:12 UTC, limli requested changes

2020-07-03 08:12 UTC, limli commented on src/test/java/com/google/step/datamanager/CommentManagerDatastoreTest.java
> +  private static final String content_B = "Hello world2";
constants should use CAPS

2020-07-03 08:12 UTC, limli commented on src/test/java/com/google/step/datamanager/CommentManagerDatastoreTest.java
> +import static org.junit.Assert.*;
don't use wildcard imports.

2020-07-03 08:12 UTC, limli commented on src/test/java/com/google/step/datamanager/CommentManagerDatastoreTest.java
> +    Assert.assertEquals(dealId, comment.dealId);
can use `assertEquals` instead of `Assert.assertEquals`

2020-07-03 08:12 UTC, limli commented on src/test/java/com/google/step/servlets/CommentServletTest.java
> +import static org.mockito.Mockito.*;
similar to above, don't use wildcard imports

2020-07-03 08:12 UTC, limli commented on src/main/java/com/google/step/servlets/CommentServlet.java
> +    if (comments == null) {
comment manager will never return null though, it'll just return an empty list

2020-07-06 02:10 UTC, limli commented on src/main/java/com/google/step/servlets/CommentServlet.java
> +      response.setStatus(HttpServletResponse.SC_NOT_FOUND);
but an empty comments is valid too

2020-07-06 02:10 UTC, limli commented on src/main/java/com/google/step/servlets/CommentServletPost.java
> +@WebServlet("/api/comments/*")
don't need the `*`

2020-07-06 02:10 UTC, limli commented on src/main/java/com/google/step/servlets/JsonFormatter.java
> +  public static Map<String, Object> getCommentMap(Comment comment) {
this can be private

2020-07-06 06:27 UTC, jyx11011 commented on src/main/java/com/google/step/datamanager/CommentManagerDatastore.java
> +  /**Deletes the comment with the given commentId */
Add a space before comment

2020-07-06 06:27 UTC, jyx11011 commented on src/main/java/com/google/step/servlets/CommentServlet.java
> +      content = request.getParameter("content");
maybe check if content is null and move it out of the try catch clause since it does not throw error?

2020-07-06 06:27 UTC, jyx11011 commented on src/test/java/com/google/step/datamanager/CommentManagerDatastoreTest.java
> +import static org.junit.Assert.*;
Try not using wildcard according to style guide.

2020-07-06 08:02 UTC, lisasgoh commented on src/main/java/com/google/step/datamanager/CommentManagerDatastore.java
> +  /**Deletes the comment with the given commentId */
which 'comment' are you talking about?

2020-07-06 08:20 UTC, limli commented on src/main/java/com/google/step/datamanager/CommentManagerDatastore.java
> +  /**Deletes the comment with the given commentId */
/** Deletes the comment with the given commentId */

I think there should be a space between the `/**` and the `Deletes`

Actually can you just run the google-java-format on this file? I just noticed some trailing spaces, import order difference and stuff

2020-07-06 08:45 UTC, lisasgoh commented on src/main/java/com/google/step/servlets/CommentServlet.java
> +      content = request.getParameter("content");
i changed to check if its null in the updateComment method

2020-07-07 07:16 UTC, limli commented
want to close this and replace with #32 and #33?

2020-07-07 07:30 UTC, SuyashLakhotia commented
@lisasgoh Can this PR be closed as per @limli's comment?

2020-07-07 07:31 UTC, closed without merging