Add indiv deal page
googleinterns/step203-2020 pull request #5
Opened 2020-06-26 07:27 UTC by lisasgoh

2020-06-26 08:32 UTC, limli commented on src/main/webapp/WEB-INF/jsp/deals.jsp
> +              <textarea style="width: 100%;" class="comment border border-info" type="text" name="comment" placeholder="Leave a comment..."></textarea>
change class to "form-control" instead of "border border-info" to be consistent with the other pages

2020-06-26 08:32 UTC, limli commented on src/main/webapp/WEB-INF/jsp/deals.jsp
> +  <div class="container">
can add a div with class "page-section" which will add a top and bottom margin

2020-06-26 08:32 UTC, limli commented on src/main/webapp/js/go-to-deal.js
> +      commentElement.className = 'comment border border-info';
add some padding in the div, the text looks very cramped

2020-06-26 08:32 UTC, limli commented on src/main/webapp/css/styles.css
> +#header-bg-img {
don't use the html id style in the common style shared by every page

2020-06-26 08:32 UTC, limli commented on src/main/webapp/js/go-to-deal.js
> +    "id": 1234,
run eslint on this file, the spacing is wrong

2020-06-30 04:17 UTC, SuyashLakhotia requested changes

2020-06-30 04:17 UTC, SuyashLakhotia commented on src/main/webapp/css/styles.css
> +}
I don't see any of these being used in the HTML or JavaScript? Am I missing something?

2020-06-30 04:17 UTC, SuyashLakhotia commented on src/main/webapp/js/go-to-deal.js
> +});
Should this use the `addLoadEvent` function from `util.js` instead like #4?

2020-07-01 10:57 UTC, SuyashLakhotia approved these changes

2020-07-01 10:57 UTC, SuyashLakhotia commented on src/main/webapp/WEB-INF/web.xml
> +    <servlet>
nit: \n before this

2020-07-02 05:41 UTC, merged