Fix tests for comment servlet
googleinterns/step203-2020 pull request #50
Opened 2020-07-13 08:33 UTC by lisasgoh

Fixed tests to match updated methods and transferred constants to TestConstants

2020-07-13 08:40 UTC, limli commented on src/main/java/com/google/step/servlets/CommentGetPostServlet.java
> +        .println(JsonFormatter.getCommentsJson(new ArrayList<Comment>(Arrays.asList(comment))));
Can you use `getCommentJson` instead?

2020-07-13 09:12 UTC, limli commented on src/test/java/com/google/step/TestConstants.java
> +  public static final String TIME_A = "Time A";
can your time be more similar to the actual time format?

2020-07-14 04:23 UTC, limli submitted a review, later dismissed

2020-07-14 05:22 UTC, SuyashLakhotia submitted a review, later dismissed

2020-07-14 06:50 UTC, SuyashLakhotia requested changes

2020-07-14 06:50 UTC, SuyashLakhotia commented on src/test/java/com/google/step/servlets/CommentServletTest.java
> +      new Comment(COMMENT_ID_A, DEAL_ID_A, USER_ID_A, UPDATE_CONTENT_A, TIME_A);
```java
private static final Comment COMMENT_A = new Comment(COMMENT_ID_A, DEAL_ID_A, USER_ID_A, CONTENT_A, TIME_A);
```

And delete `UPDATE_CONTENT_A` altogether?

2020-07-14 10:42 UTC, SuyashLakhotia approved these changes

2020-07-14 20:26 UTC, merged