Implement Restaurant page (frontend) with maps api to search for places
googleinterns/step203-2020 pull request #62
Opened 2020-07-14 10:10 UTC by limli

![Screenshot 2020-07-14 at 5 56 38 PM](https://user-images.githubusercontent.com/39252823/87412959-392e7d80-c5fc-11ea-9a7e-8bedfc3f2360.png)

![Screenshot 2020-07-14 at 5 55 03 PM](https://user-images.githubusercontent.com/39252823/87412832-14d2a100-c5fc-11ea-9dc1-699b6587b29d.png)

2020-07-16 07:25 UTC, jyx11011 approved these changes

2020-07-16 12:20 UTC, lisasgoh approved these changes

2020-07-17 10:49 UTC, SuyashLakhotia requested changes

2020-07-17 10:49 UTC, SuyashLakhotia commented on src/main/webapp/js/util.js
> +/**
Should you also replace the copy of this you have in search or elsewhere in the codebase with this?

2020-07-17 10:50 UTC, SuyashLakhotia commented on src/main/webapp/js/util.js
> +/**
Feel free to do this in a follow up PR.

2020-07-17 10:50 UTC, SuyashLakhotia approved these changes

2020-07-18 04:08 UTC, merged