Update DealDetailServlet to get real restaurants & tags, and add authentication to delete
googleinterns/step203-2020 pull request #71
Opened 2020-07-16 09:12 UTC by limli

GET requests now returns real restaurants/tags instead of placeholders
DELETE now only works if the user is authorised, and is deleting a deal he posted.
and tests are added

2020-07-20 03:10 UTC, jyx11011 submitted a review, later dismissed

2020-07-20 10:14 UTC, SuyashLakhotia requested changes

2020-07-20 10:14 UTC, SuyashLakhotia commented on src/main/java/com/google/step/servlets/DealDetailServlet.java
> +    // user can only delete deals he created
```suggestion
    // user can only delete deals they created
```

2020-07-20 10:14 UTC, SuyashLakhotia commented on src/test/java/com/google/step/servlets/DealDetailServletTest.java
> +  public void testDoDelete_sucess() throws IOException {
```suggestion
  public void testDoDelete_success() throws IOException {
```

2020-07-20 10:14 UTC, SuyashLakhotia commented on src/test/java/com/google/step/servlets/DealDetailServletTest.java
> +    verify(mockResponse).setStatus(HttpServletResponse.SC_OK);
Verify response?

2020-07-20 10:14 UTC, SuyashLakhotia commented on src/test/java/com/google/step/servlets/DealDetailServletTest.java
> +    verify(mockResponse).setStatus(HttpServletResponse.SC_NOT_FOUND);
Add a NOT_FOUND test for doDelete?

2020-07-21 06:11 UTC, SuyashLakhotia approved these changes

2020-07-21 06:12 UTC, merged