Add isFollowing in follow manager and servlet and tests
googleinterns/step203-2020 pull request #74
Opened 2020-07-17 02:54 UTC by jyx11011

2020-07-17 03:00 UTC, limli commented on src/main/java/com/google/step/servlets/FollowServlet.java
> +    String followerIdString = request.getParameter("followerId");
get form UserService authentication instead?

2020-07-17 03:00 UTC, limli commented on src/main/java/com/google/step/datamanager/FollowManagerDatastore.java
> +  private boolean isFollowing(long followerId, long followeeId, String followeeFieldName) {
rename to isFollowingSomething to follow the other private methods?

2020-07-17 03:00 UTC, limli commented on src/main/java/com/google/step/servlets/FollowServlet.java
> +    if (request.getParameter("restaurantId") != null) {
instead of getting from paramter, want to follow the doPost and check `pathInfo.startsWith("restaurants/")` ?

2020-07-17 03:51 UTC, jyx11011 commented on src/main/java/com/google/step/servlets/FollowServlet.java
> +    String followerIdString = request.getParameter("followerId");
can it be getting any users's following? not the logged in user only

2020-07-17 04:27 UTC, limli commented on src/main/java/com/google/step/servlets/FollowServlet.java
> +    String followerIdString = request.getParameter("followerId");
oh ok sure. Then no need authentication.

2020-07-17 10:33 UTC, lisasgoh commented on src/test/java/com/google/step/datamanager/FollowManagerDatastoreTest.java
> +    manager.followUser(USER_ID_A, USER_ID_B);
maybe rename manager to followManager?

2020-07-17 10:35 UTC, lisasgoh commented on src/test/java/com/google/step/servlets/FollowServletTest.java
> +    when(followManager.isFollowingRestaurant(USER_ID_A, RESTAURANT_ID_A)).thenReturn(true);
and maybe followManager to mockFollowManager

2020-07-20 04:26 UTC, limli submitted a review, later dismissed

2020-07-20 09:58 UTC, SuyashLakhotia requested changes

2020-07-20 09:58 UTC, SuyashLakhotia commented on src/main/java/com/google/step/datamanager/FollowManagerDatastore.java
> +  private boolean isFollowingSomething(long followerId, long followeeId, String followeeFieldName) {
```suggestion
  private boolean isFollowing(long followerId, long followeeId, String followeeFieldName) {
```

2020-07-20 09:58 UTC, SuyashLakhotia commented on src/main/java/com/google/step/servlets/FollowServlet.java
> +      response.setStatus(HttpStatusCodes.STATUS_CODE_BAD_REQUEST);
Let's be consistent and return `SC_BAD_REQUEST` instead of `STATUS_CODE_BAD_REQUEST`? Same everywhere else in this file.

2020-07-20 09:58 UTC, SuyashLakhotia commented on src/main/java/com/google/step/servlets/FollowServlet.java
> +
Remove this \n

2020-07-20 09:58 UTC, SuyashLakhotia commented on src/main/java/com/google/step/servlets/FollowServlet.java
> +
Remove this \n

2020-07-20 09:58 UTC, SuyashLakhotia commented on src/main/java/com/google/step/servlets/FollowServlet.java
> +      response.setStatus(HttpStatusCodes.STATUS_CODE_BAD_REQUEST);
And the tests too, please

2020-07-21 06:12 UTC, SuyashLakhotia approved these changes

2020-07-21 07:18 UTC, merged