Front end for home page authentication
googleinterns/step203-2020 pull request #83
Opened 2020-07-20 04:23 UTC by lisasgoh

![Screenshot 2020-07-20 at 12 10 02 PM](https://user-images.githubusercontent.com/42923450/87899354-8048c280-ca83-11ea-9485-c8af5a451a64.png)
If the user is not logged in, the sections other than trending will be unavailable to view.

2020-07-20 04:47 UTC, jyx11011 commented on src/main/webapp/js/home-page.js
> +
nit: trailing spaces

2020-07-20 09:53 UTC, SuyashLakhotia requested changes

2020-07-20 09:53 UTC, SuyashLakhotia commented on src/main/java/com/google/step/servlets/HomePageServlet.java
> +      userId = user.id;
Why the separation of declaration and assignment?

2020-07-20 09:53 UTC, SuyashLakhotia commented on src/main/webapp/js/home-page.js
> +    homePageData = homePage[homePageSections[i]];
```suggestion
    const homePageData = homePage[homePageSections[i]];
```

Or `let`?

2020-07-21 06:13 UTC, SuyashLakhotia submitted a review, later dismissed

2020-07-23 01:58 UTC, SuyashLakhotia approved these changes

2020-07-23 06:29 UTC, merged