Add a form to edit deal (frontend)
googleinterns/step203-2020 pull request #95
Opened 2020-07-21 06:10 UTC by limli

![Screenshot 2020-07-21 at 1 56 14 PM](https://user-images.githubusercontent.com/39252823/88019044-76928e00-cb5b-11ea-9abc-edc95168aa0f.png)

The search bar logic is from the file restaurant-search-util.js, which is now shared with the search implementation for add-deal.

2020-07-21 07:15 UTC, jyx11011 commented on src/main/webapp/js/go-to-deal.js
> +  if (form.checkValidity() === false || !checkDatesOrdered()) {
!form.checkValidity

2020-07-24 05:56 UTC, lisasgoh commented on src/main/webapp/js/restaurant-search-util.js
> +  if (query == '') {
use ===?

2020-07-24 05:57 UTC, lisasgoh submitted a review, later dismissed

2020-07-24 06:33 UTC, jyx11011 submitted a review, later dismissed

2020-07-27 04:55 UTC, SuyashLakhotia requested changes

2020-07-27 04:55 UTC, SuyashLakhotia commented on src/main/webapp/js/go-to-deal.js
> +
Should this logic be common with the page that adds deals as well? Is there other validation logic that could be made common too?

2020-07-27 08:47 UTC, SuyashLakhotia approved these changes

2020-07-27 09:50 UTC, merged